version: '3.2'
services:
  clash-tproxy:
    container_name: clash
    image: gdfsnhsw/clash-tproxy:premium-latest
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: unless-stopped
    privileged: true
    #entrypoint: tail -f /dev/null
    #command: tail -f /dev/null
    volumes:
      - ./clash_config:/clash_config
    environment:
      - TZ=Asia/Shanghai
      - DNS_MODE=fake-ip
      - ROUTE_MODE=redir-tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      _dMACvLan:
        ipv4_address: 192.168.88.70
    dns:
      - 114.114.114.114

networks:
  _dMACvLan:
    external:
      name: _dMACvLan
